### ISSUE TITLE
Add undocumented `app.openFast()` method

### ISSUE THREAD

**Issue by zlovatt** [docsforadobe/after-effects-scripting-guide#22]
Be sure to add the admonition that this is undocumented!

**Comment by bjg2** [comment]
anyone has any idea how app.open() differs from app.openFast() ?

**Comment by Nico-Duduf** [comment]
Done, PR #35

I've measured it to be noticeably faster with many small projects (which open in less than 2 seconds anyway). The example in the doc in the PR is a simple script to measure the difference.
